/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

/**
 *
 * @author USER
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Newtrainer1 = new javax.swing.JButton();
        udtrainer = new javax.swing.JButton();
        alltrainer = new javax.swing.JButton();
        collection1 = new javax.swing.JButton();
        recipt = new javax.swing.JButton();
        add = new javax.swing.JButton();
        udequipment = new javax.swing.JButton();
        viewall = new javax.swing.JButton();
        Newmember = new javax.swing.JButton();
        Udmember = new javax.swing.JButton();
        allmember = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(580, 373));
        getContentPane().setLayout(null);

        Newtrainer1.setText("Add new trainer");
        Newtrainer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Newtrainer1ActionPerformed(evt);
            }
        });
        getContentPane().add(Newtrainer1);
        Newtrainer1.setBounds(150, 100, 120, 23);

        udtrainer.setText("Update\\delete trainer");
        udtrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udtrainerActionPerformed(evt);
            }
        });
        getContentPane().add(udtrainer);
        udtrainer.setBounds(150, 140, 120, 23);

        alltrainer.setText("All Trainer");
        alltrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alltrainerActionPerformed(evt);
            }
        });
        getContentPane().add(alltrainer);
        alltrainer.setBounds(150, 180, 120, 23);

        collection1.setText("Collection");
        collection1.setMaximumSize(new java.awt.Dimension(115, 23));
        collection1.setMinimumSize(new java.awt.Dimension(115, 23));
        collection1.setPreferredSize(new java.awt.Dimension(137, 23));
        collection1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collection1ActionPerformed(evt);
            }
        });
        getContentPane().add(collection1);
        collection1.setBounds(420, 200, 120, 23);

        recipt.setText("Recipt");
        recipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reciptActionPerformed(evt);
            }
        });
        getContentPane().add(recipt);
        recipt.setBounds(420, 230, 120, 23);

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(280, 140, 120, 23);

        udequipment.setText("Update\\delete equipment");
        udequipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udequipmentActionPerformed(evt);
            }
        });
        getContentPane().add(udequipment);
        udequipment.setBounds(280, 220, 120, 23);

        viewall.setText("All Equipments");
        viewall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallActionPerformed(evt);
            }
        });
        getContentPane().add(viewall);
        viewall.setBounds(280, 180, 120, 23);

        Newmember.setText("Add new member");
        Newmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewmemberActionPerformed(evt);
            }
        });
        getContentPane().add(Newmember);
        Newmember.setBounds(10, 60, 120, 23);

        Udmember.setText("Delete Member");
        Udmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UdmemberActionPerformed(evt);
            }
        });
        getContentPane().add(Udmember);
        Udmember.setBounds(10, 100, 120, 23);

        allmember.setText("All member");
        allmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allmemberActionPerformed(evt);
            }
        });
        getContentPane().add(allmember);
        allmember.setBounds(10, 140, 120, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MEMBER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 130, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TRINER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 60, 130, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EQUIPMENT");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 90, 130, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("REPORT");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 150, 130, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/in1.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -20, 580, 360);

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Newtrainer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Newtrainer1ActionPerformed
        // TODO add your handling code here:
        newtrainer g=new newtrainer();
        g.setVisible(true);
    }//GEN-LAST:event_Newtrainer1ActionPerformed

    private void udtrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udtrainerActionPerformed
        // TODO add your handling code here:
        udtrainer h=new udtrainer();
        h.setVisible(true);
    }//GEN-LAST:event_udtrainerActionPerformed

    private void alltrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alltrainerActionPerformed
        // TODO add your handling code here:
        AllTrainer i=new AllTrainer();
        i.setVisible(true);
    }//GEN-LAST:event_alltrainerActionPerformed

    private void NewmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewmemberActionPerformed

        this.dispose();
        Newmember b= new Newmember();
        b.setVisible(true);

    }//GEN-LAST:event_NewmemberActionPerformed

    private void UdmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UdmemberActionPerformed
        // TODO add your handling code here:
        this.dispose();
        udmember c= new udmember();
        c.setVisible(true);

    }//GEN-LAST:event_UdmemberActionPerformed

    private void allmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allmemberActionPerformed
        allmember d=new allmember();
        d.setVisible(true);

    }//GEN-LAST:event_allmemberActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
         this.dispose();
        addequ e=new addequ();
        e.setVisible(true);
    }//GEN-LAST:event_addActionPerformed

    private void udequipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udequipmentActionPerformed
        // TODO add your handling code here:
         this.dispose();
        udequip f=new udequip();
        f.setVisible(true);
    }//GEN-LAST:event_udequipmentActionPerformed

    private void collection1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collection1ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        collection j=new collection();
        j.setVisible(true);
    }//GEN-LAST:event_collection1ActionPerformed

    private void reciptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reciptActionPerformed
        // TODO add your handling code here:
         
        Recipt k=new Recipt();
        k.setVisible(true);

    }//GEN-LAST:event_reciptActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void viewallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallActionPerformed
        AllEquipment l=new AllEquipment();
        l.setVisible(true);
    }//GEN-LAST:event_viewallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Newmember;
    private javax.swing.JButton Newtrainer1;
    private javax.swing.JButton Udmember;
    private javax.swing.JButton add;
    private javax.swing.JButton allmember;
    private javax.swing.JButton alltrainer;
    private javax.swing.JButton collection1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton recipt;
    private javax.swing.JButton udequipment;
    private javax.swing.JButton udtrainer;
    private javax.swing.JButton viewall;
    // End of variables declaration//GEN-END:variables
}
