/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;
import java.sql.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class newtrainer extends javax.swing.JFrame {

    /**
     * Creates new form newtrainer
     */
    public newtrainer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        NAME = new javax.swing.JLabel();
        AGE = new javax.swing.JLabel();
        GENDER = new javax.swing.JLabel();
        PACKAGE = new javax.swing.JLabel();
        CONTACT = new javax.swing.JLabel();
        EMAIL = new javax.swing.JLabel();
        DOJ = new javax.swing.JLabel();
        jTextNAME = new javax.swing.JTextField();
        jTextAGE = new javax.swing.JTextField();
        jComboGENDER = new javax.swing.JComboBox<>();
        jTextPACKAGE = new javax.swing.JTextField();
        jTextCONTACT = new javax.swing.JTextField();
        jTextEMAIL = new javax.swing.JTextField();
        jTextDOJ = new javax.swing.JTextField();
        TRAINERID = new javax.swing.JLabel();
        jTextTRAINERID = new javax.swing.JTextField();
        CANCEL = new javax.swing.JButton();
        SAVE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setOpaque(false);

        NAME.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NAME.setForeground(new java.awt.Color(255, 255, 255));
        NAME.setText("Trainer Name");

        AGE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AGE.setForeground(new java.awt.Color(255, 255, 255));
        AGE.setText("AGE");

        GENDER.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GENDER.setForeground(new java.awt.Color(255, 255, 255));
        GENDER.setText("Gender");

        PACKAGE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PACKAGE.setForeground(new java.awt.Color(255, 255, 255));
        PACKAGE.setText("Package Yearly");

        CONTACT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CONTACT.setForeground(new java.awt.Color(255, 255, 255));
        CONTACT.setText("Contact Number");

        EMAIL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EMAIL.setForeground(new java.awt.Color(255, 255, 255));
        EMAIL.setText("Email");

        DOJ.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DOJ.setForeground(new java.awt.Color(255, 255, 255));
        DOJ.setText("Date of Joining");

        jTextNAME.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextAGE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jComboGENDER.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboGENDER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One. . .", "Male", "Female", "Common" }));

        jTextPACKAGE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextCONTACT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextEMAIL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextDOJ.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        TRAINERID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TRAINERID.setForeground(new java.awt.Color(255, 255, 255));
        TRAINERID.setText("Trainer ID");

        jTextTRAINERID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        CANCEL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CANCEL.setText("CANCEL");
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });

        SAVE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD TRAINER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PACKAGE)
                            .addComponent(CONTACT)
                            .addComponent(EMAIL)
                            .addComponent(DOJ)
                            .addComponent(TRAINERID)
                            .addComponent(SAVE, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CANCEL)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextDOJ)
                                .addComponent(jTextEMAIL)
                                .addComponent(jTextCONTACT)
                                .addComponent(jTextTRAINERID)
                                .addComponent(jTextPACKAGE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NAME)
                            .addComponent(AGE)
                            .addComponent(GENDER))
                        .addGap(108, 108, 108)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboGENDER, 0, 141, Short.MAX_VALUE)
                            .addComponent(jTextNAME)
                            .addComponent(jTextAGE))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(164, 164, 164))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAME)
                    .addComponent(jTextNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AGE)
                    .addComponent(jTextAGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GENDER)
                    .addComponent(jComboGENDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PACKAGE)
                    .addComponent(jTextPACKAGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CONTACT)
                    .addComponent(jTextCONTACT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EMAIL)
                    .addComponent(jTextEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOJ)
                    .addComponent(jTextDOJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TRAINERID)
                    .addComponent(jTextTRAINERID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SAVE)
                    .addComponent(CANCEL))
                .addGap(32, 32, 32))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 11, 456, 511);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/crossfit-equipment.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 530, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        int x=0;
        String s1=jTextNAME.getText();
        String s2=jTextAGE.getText();
        String s3=(String) jComboGENDER.getSelectedItem();
        String s4=jTextPACKAGE.getText();
        String s5=jTextCONTACT.getText();
        String s6=jTextEMAIL.getText ();
        String s7=jTextDOJ.getText();
        String s8=jTextTRAINERID.getText();

        try{
            String host="jdbc:derby://localhost:1527/MemberForm";
            String uname="users";
            String pw="users";
            Connection con=DriverManager.getConnection(host,uname,pw);
            PreparedStatement ps= con.prepareStatement("INSERT INTO TRAINER VALUES (?,?,?,?,?,?,?,?)");
            ps.setString(1, s1);
            ps.setString(2, s2);
            ps.setString(3, s3);
            ps.setString(4, s4);
            ps.setString(5, s5);
            ps.setString(6, s6);
            ps.setString(7, s7);
            ps.setString(8, s8);
            ps.executeUpdate();
            x++;
            if(x>0){
                JOptionPane.showMessageDialog(this, "Data saved!");

            }

        }catch(Exception err){
            JOptionPane.showMessageDialog(this, err.getMessage());
        }

    }//GEN-LAST:event_SAVEActionPerformed

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELActionPerformed
        this.dispose();   
    }//GEN-LAST:event_CANCELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newtrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newtrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newtrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newtrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newtrainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AGE;
    private javax.swing.JButton CANCEL;
    private javax.swing.JLabel CONTACT;
    private javax.swing.JLabel DOJ;
    private javax.swing.JLabel EMAIL;
    private javax.swing.JLabel GENDER;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel PACKAGE;
    private javax.swing.JButton SAVE;
    private javax.swing.JLabel TRAINERID;
    private javax.swing.JComboBox<String> jComboGENDER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextAGE;
    private javax.swing.JTextField jTextCONTACT;
    private javax.swing.JTextField jTextDOJ;
    private javax.swing.JTextField jTextEMAIL;
    private javax.swing.JTextField jTextNAME;
    private javax.swing.JTextField jTextPACKAGE;
    private javax.swing.JTextField jTextTRAINERID;
    // End of variables declaration//GEN-END:variables
}
